firefly/arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200 

  # Position Controllers ---------------------------------------
  J1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J1
    pid: {p: 0.5, i: 0, d: 0.005}

  J2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J2
    pid: {p: 1, i: 0, d: 0.008}

  J3_position_controller:
    type: effort_controllers/JointPositionController
    joint: J3
    pid: {p: 5, i: 0.5, d: 0.2}

  J4_position_controller:
    type: effort_controllers/JointPositionController
    joint: J4
    pid: {p: 1, i: 0, d: 0.008}

  J5_position_controller:
    type: effort_controllers/JointPositionController
    joint: J5
    pid: {p: 0.5, i: 0, d: 0.005}



