firefly/arm:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500 

  spring_controller:
    type: effort_controllers/JointPositionController 
    joint: spring_joint
    pid: {p: 50, i: 0, d: 1}
